### ISSUE TITLE
Part-time Engineer

### ISSUE THREAD

**Issue by dbettin** [tagnifi/job-descriptions#1]
[TagniFi](https://tagnifi.com) is building a modern financial data platform for finance and investment professionals. We deliver our data to clients via our API, web console, and Excel plugin. We're looking for a part-time engineer to help us build new datasets and features for our platform. 

Additional Info:

We are looking for an engineer that can help us with our entire stack  Our front-end is developed in Vue and Typescript and our backend is predominantly developed in Rust and Postgres on GCP. Some level of experience with these technologies is required. If you have Excel plugin development experience that would be awesome too. 
 
Examples of projects we might have you work on:  Using Rust to parse different structured and unstructured data formats, writing jobs that verify our data quality, or working on our web console to add new search capabilities.
 
The role will start out as part-time but does have the possibility of leading to more hours. We work remotely, while we prefer you to be located in North America, we are open to other locations.
 
If this sounds interesting, please send an email to jobs@tagnifi.com. Links to Github, LinkedIn, and/or a paragraph detailing an engineering challenge you have recently faced are highly encouraged.

**Comment by dbettin** [comment]
At this time, we are not interested in consultancy companies to fill this role.  We are only interested in an individual engineer that is able to work part-time with the ability to handle more than part-time hours as needed.

**Comment by shirshak55** [comment]
wow

**Comment by decentninja** [comment]
Applied <3

**Comment by ciehanski** [comment]
Applied as well. 💪

**Comment by leadstar116** [comment]
Sounds great! Applied!

**Comment by Luckey-Elijah** [comment]
Looks awesome! Sent in an application. Hope o hear from you guys soon!

**Comment by dbettin** [comment]
The position has been filled.  Thank you for all of the interest.
